#!/bin/sh

EXTRA_ARGS=$@

cmake \
 -D CMAKE_BUILD_TYPE:STRING=DEBUG \
 -D CMAKE_C_FLAGS:STRING="-fPIC" \
 -D CMAKE_CXX_FLAGS:STRING="-fPIC" \
 -D CMAKE_Fortran_FLAGS:STRING="-fPIC" \
 -D Trilinos_ENABLE_Epetra:BOOL=ON \
 -D Trilinos_ENABLE_EpetraExt:BOOL=ON \
 -D Trilinos_ENABLE_AztecOO:BOOL=ON \
 -D Trilinos_ENABLE_Ifpack:BOOL=ON \
 -D Trilinos_ENABLE_ML:BOOL=ON \
 -D Trilinos_ENABLE_Amesos:BOOL=ON \
 -D Trilinos_ENABLE_NOX:BOOL=ON \
 -D Trilinos_ENABLE_Anasazi:BOOL=ON \
 -D Trilinos_ENABLE_Komplex:BOOL=ON \
 -D Trilinos_ENABLE_Claps:BOOL=ON \
 -D Trilinos_ENABLE_TESTS:BOOL=ON \
 -D DART_TESTING_TIMEOUT:STRING=600 \
 -D CMAKE_INSTALL_PREFIX:STRING=/opt/packages/trilinos \
  $EXTRA_ARGS ..
